apiVersion: apps/v1
kind: Deployment
metadata:
  name: circle-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: circle-auth
  template:
    metadata:
      labels:
        app: circle-auth
    spec:
      containers:
        - name: circle-auth
          image: kohee/circle-auth:latest
          ports:
            - containerPort: 80
          env:
            - name: APP_ID_API_URL
              valueFrom:
                secretKeyRef:
                  name: circle-auth-secret
                  key: APP_ID_API_URL
---
apiVersion: v1
kind: Service
metadata:
  name: circle-auth
  annotations:
    dev.okteto.com/auto-ingress: "private"
spec:
  selector:
    app: circle-auth
  type: NodePort
  ports:
    - port: 80
