apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  ingressClassName: "nginx"
  defaultBackend:
    service:
      name: circle-auth
      port:
        number: 80
  rules:
    - http:
        paths:
          - backend:
              service:
                name: circle-auth
                port:
                  number: 80
            pathType: Prefix
            path: "/"